### ISSUE TITLE
Can't "use strict" with store.js

### ISSUE THREAD

**Issue by avivgiladi** [marcuswestin/store.js#111]
The function ieKeyFix(key)  is located in a place where it's not allowed with "use strict" mode.
Moving it to an upper location solves the issue. Maybe it's worth changing it in the source

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released!

If you update to the [latest version](https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will get this fix plus a bunch more :)
