### ISSUE TITLE
Does store.js support mobile Safari?

### ISSUE THREAD

**Issue by fchristant** [marcuswestin/store.js#113]
I love this library and have been testing it in several browsers and on a few devices. Both my own test and the official test you provide, however, fail in mobile safari (iPhone5, iOS 8). 

I was wondering if this is a known issue and/or if there is a workaround? Mobile Safari is a pretty important browser nowadays. Or does Mobile Safari simply not support any of the storage modes?

**Comment by dhunink** [comment]
I actually have it implemented on https://tpgrf.nl/testserver/alpha/topotrainer/nederland/. Works like a charm (iPhone 6, iOS 8.1)

**Comment by fchristant** [comment]
Oops, looks like a user error. I had mobile Safari in private mode, works now if I set it to normal mode.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for Safari private mode.

If you update to the latest version using the [v1 backcompatible build](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)
