### ISSUE TITLE
store.js requires unsafe javascript eval, breaks CSP headers

### ISSUE THREAD

**Issue by FredKSchott** [marcuswestin/store.js#115]
in commit 1ffa6f49bb767a6333c6818c52ddeb617e2b3072 code was introduced to evaluate a string as JavaScript code. This unnecessarily prevents anyone who has implemented CSP headers from using store.js, since adding "unsafe-eval" as a valid javascript script source defeats the main point of CSP headers in the first place.

```diff
// commit 1ffa6f49bb767a6333c6818c52ddeb617e2b3072
-})(this.window || global);
+})(Function('return this')());
```
See: http://content-security-policy.com/

**Comment by nbubna** [comment]
Not to be pedantic, but store.js does not request unsafe javascript eval. There is nothing whatsoever unsafe about this use of the Function constructor.  So, while i sympathize with the actual problem (that the change breaks CSP headers), this is technically a bug in the parser/logic that is claiming this to be unsafe.

Sorry, i realize that's not the most helpful response. It just bugs me that eval and the Function constructor get such a bad wrap for being "unsafe", when there are legitimate, fully-safe ways to use them.

Ok, stepping back now to let Marcus handle this. :)

**Comment by marcuswestin** [comment]
That's annoying. I've had no end of issues due to module loading systems.


I would very happily accept a PR that fixes this and cites a reliable "this is how to do cross-module-loader exports reliably".


-- while mobile

**Comment by whitehat101** [comment]
I've been lurking this project's issues for a while now, so I can appreciate the module loading frustrations.

Instead of shooting for a one-size-fits-all module loading solution, what about distributing a couple js files, "normal" store.js, AMD's style, etc. It's more files, but it might be a manageable way to make everyone happy.

**Comment by marcuswestin** [comment]
Thanks for throwing your hat into the ring :)



That's an interesting thought, but is there really not a single, good solution out there used by other popular libraries?


I feel wary to introduce the innevitable confusion and complexity of multiple files.


-- while mobile

**Comment by marcuswestin** [comment]
Thanks to @whitehat101 this should be fixed as of 7c65e0a646c9. @FredKSchott, can you please verify and/or close?

Thanks for the patience!

**Comment by FredKSchott** [comment]
yup, all fixed. Awesome stuff guys!

**Comment by marcuswestin** [comment]
Brilliant, thanks for following up Fred.


Cheers!


-- while mobile
