### ISSUE TITLE
Hierarchy Request & Permission Denied Error on storageOwner.appendChild(storage) in IE

### ISSUE THREAD

**Issue by szafar-techtronix** [marcuswestin/store.js#118]
In the following method in store.js, Internet Explorer on some machines show the Permission Denied and Hierarchy Request Error on the line storageOwner.appendChild(storage)
It works just fine on some machines but on some machines it is not allowing the page to load. There is an ajax call on the page and it ends up giving the above error in console and sometimes with an alert saying 'There was an error to load this page. Please check idle timer.' It seems that the issue is related to localStorage being disabled in some browsers on some machines. It works absolutely fine in other browsers like Mozilla, Chrome etc. This issue happens on some IE version 10/11

![hierarchyrequesterror](https://cloud.githubusercontent.com/assets/6292962/6164431/f4c8294c-b2c0-11e4-8031-cd8e51e9f87a.png)
![permissiondeniederror](https://cloud.githubusercontent.com/assets/6292962/6164432/f4c9c018-b2c0-11e4-82f8-f0575f6d78d9.png)

```
    function withIEStorage(storeFunction) {
        return function() {
            var args = Array.prototype.slice.call(arguments, 0)
            args.unshift(storage)
            // See http://msdn.microsoft.com/en-us/library/ms531081(v=VS.85).aspx
            // and http://msdn.microsoft.com/en-us/library/ms531424(v=VS.85).aspx
            storageOwner.appendChild(storage)
            storage.addBehavior('#default#userData')
            storage.load(localStorageName)
            var result = storeFunction.apply(store, args)
            storageOwner.removeChild(storage)
            return result
        }
    }
```

Can anyone help?

**Comment by marcuswestin** [comment]
Hey,

Sorry you're having trouble, I imagine it's frustrating.

Can you provide a repro? It's very hard to help you without additional information.

Did you search this repo's issues? Check e.g #84 and #82, there may be others.

**Comment by axar** [comment]
This continues to happen.

I wanted to test to see if the site worked fine if "Enable DOM Storage" is checked off from IE options. I can re-create this on all machine I have tried to use with DOM storage disabled. store.enable says true, while it fails to run with above error.

**Comment by seryh** [comment]
my fix:
```javascript
    function withIEStorage(storeFunction) {
      return function() {
        try {
          var args = Array.prototype.slice.call(arguments, 0);
          args.unshift(storage);
          // See http://msdn.microsoft.com/en-us/library/ms531081(v=VS.85).aspx
          // and http://msdn.microsoft.com/en-us/library/ms531424(v=VS.85).aspx
          storageOwner.appendChild(storage);
          storage.addBehavior('#default#userData');
          storage.load(localStorageName);
          var result = storeFunction.apply(store, args);
          storageOwner.removeChild(storage);
          return result;
        } catch(e) {
          return function(){return null;};
        }
      };
```

**Comment by writer0713** [comment]
@seryh 
Your code cannot resolve this problem. 
I got the same problem in IE10.
And the problem was because of IE10 private setting. (I don't know exactly which setting makes this problem.)
However, after clicking 'Restore advanced settings' button, this problem is solved.

**Comment by marcuswestin** [comment]
Looks like this was resolved. Feel free to reopen with more info.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with pluggable fallback backing storages which ensure that store.js always works in any environment.

If you update to the [v2 backcompat version](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)
