### ISSUE TITLE
Fall back to in-memory storage

### ISSUE THREAD

**Issue by mikemintz** [marcuswestin/store.js#119]
Ideally, store.js would automatically fall back to an in-memory storage object when persistent storage is not supported. Without this, in order to support Safari private browsing, I have to wrap every call to store with something like this:

``` javascript
var memStore = {};
...
var user = store.enabled ? store.get('user') : memStore['user'];
```

**Comment by nbubna** [comment]
Agreed! (that's what store2 does)

**Comment by evitolins** [comment]
Hey guys... you might be interested in an extension I wrote that incorporates that concept, and a few other enhancements I was working on.

https://github.com/evitolins/StoreFront.js

**Comment by Download** [comment]
Or in [memorystorage](https://download.github.io/memorystorage), a small memory-backed implementation of the Web Storage API that is a drop-in replacement for localStorage.

**Comment by marcuswestin** [comment]
store.js v2 is almost complete, and will have a memory storage option, among a bunch of additional addon features: https://github.com/marcuswestin/store.js/tree/v2-dev/storage, https://github.com/marcuswestin/store.js/tree/v2-dev/addon

**Comment by marcuswestin** [comment]
Stay tuned for version 2 release in the new year, or see https://github.com/marcuswestin/store.js/tree/v2-dev?files=1 for a preview of the release candidate

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released!

If you update to the latest version you get this functionality plus a bunch more :)
