### ISSUE TITLE
localStorage vs sessionStorage

### ISSUE THREAD

**Issue by gongzhitaao** [marcuswestin/store.js#126]
I think it might be good to provide an option to set the storage type (or switch between the two)
1. `localStorage` is persistent and per domain
2. `sessionStorage` is non-persistent and per tab/page

Both have their own applications.

Suggested API change:

```
// type -- str, either "localStorage" or sessionStorage"
store.use(type)
```

**Comment by nbubna** [comment]
Can't resist pointing out that [store2](https://github.com/nbubna/store) supports sessionStorage, albeit with slightly different syntax. :)

**Comment by gongzhitaao** [comment]
@nbubna Already switch to store2 :D.

**Comment by marcuswestin** [comment]
store.js v2 is almost complete, and has a session storage option (among a bunch of additional addon features - see https://github.com/marcuswestin/store.js/tree/v2-dev/storage & https://github.com/marcuswestin/store.js/tree/v2-dev/addon)

**Comment by marcuswestin** [comment]
This will be in the v2 release in the new year. See https://github.com/marcuswestin/store.js/tree/v2-dev?files=1 for a preview of the release candidate

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released!

If you update to the [latest version](https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)

**Comment by marcuswestin** [comment]
The docs explain how to create a custom build - to get one that only uses sessionStorage, you can do this:

```js
// Example custom build usage:
var engine = require('../store-engine')
var storages = [require('store/storages/sessionStorage')
var plugins = []
var store = engine.createStore(storages, plugins)
store.set('foo', 'bar')
```
