### ISSUE TITLE
Error in line 49 in FF 3.6.13

### ISSUE THREAD

**Issue by StevenBlack** [marcuswestin/store.js#13]
Hi Marcus,

Line 49 in Store.js 
49  if (localStorageName in win && win[localStorageName]) {

crashes with "Security error code: 1000" if the following option is set in About:Config

  dom.storage.enabled : false

Specifically, it is the segment 
   win[localStorageName]
that causes this to barf.

So we need a more reliable way to test for this.

**Comment by FrankFan** [comment]
```javascript
isLocalStorageSupported = function () {
        var testKey = 'test',
            storage = window.sessionStorage;
        try {
            storage.setItem(testKey, 'testValue');
            storage.removeItem(testKey);
            return true;
        } catch (error) {
            return false;
        }
    }
```

this code snippet will be better
