### ISSUE TITLE
Throw error if .clear is called with arguments

### ISSUE THREAD

**Issue by adam-lynch** [marcuswestin/store.js#130]
Would you be against that? It would help idiots like me who make the mistake of calling `store.clear('key')` instead of `store.remove('key')` and then deploy it to production.

**Comment by marcuswestin** [comment]
I would be in favor of adding `store.clearAll`, and removing store.clear from the docs (but keep the function for backwards compatibility)

**Comment by marcuswestin** [comment]
Store version 2 has removed clear and implemented clearAll. The backcompat add-on still implements the old clear. Stay tuned for a v2 release in the new year, or see https://github.com/marcuswestin/store.js/tree/v2-dev?files=1 for a preview of the release candidate

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released!

If you update to the [latest version](https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)
