### ISSUE TITLE
store.disabled=true when userData is unavailable in IE

### ISSUE THREAD

**Issue by kachkaev** [marcuswestin/store.js#132]
IE 6 & 7 on real machines are quite rare these days among those who test websites. Some web developers including myself use [IETester](http://www.my-debugbar.com/wiki/IETester/HomePage) to check if everything's working in old browsers – this normally requires only one virtual machine with Windows.

Unfortunately, IETester has some problems with userData in IE6 and IE7 modes – [that does not seem to be available there.](https://www.google.com/search?q=ietester%20userdata) UserData can also be disabled in native IEs, [according to the docs on IE policy settings](https://technet.microsoft.com/en-us/library/Bb457144.aspx).

It would be nice if store.js considered the possible absence of userData and marked itself as disabled accordingly. Currently, an unexpected exception is thrown when you try to run the following:

``` js
if (!store.disabled) {
    store.set("key", "value");
}
```

(this applies to IE6 and IE7 tabs in IETester + might also happen in real IEs that have odd security settings)

**Comment by marcuswestin** [comment]
I believe this should work as you expect in master, thanks to this block at the bottom of `store.js`:

```
	try {
		var testKey = '__storejs__'
		store.set(testKey, testKey)
		if (store.get(testKey) != testKey) { store.disabled = true }
		store.remove(testKey)
	} catch(e) {
		store.disabled = true
	}
	store.enabled = !store.disabled
```

Feel free to reopen with more info.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for fallback backing storages that ensure that store always works.

If you update to the [v1 backcompatible build](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)
