### ISSUE TITLE
Best practice for adding to store.js arrays?

### ISSUE THREAD

**Issue by klombomb** [marcuswestin/store.js#134]
For me the push method isn't working so i was wondering what works well for you guys when starting off with an empty array?

**Comment by dhunink** [comment]
Why is the push method not working for you?
Does a snippet like the following makes any sense for you?

    grArr = new Array()
    for (var key in gLayer.graphics){
	  grArr.push({'attributes': gLayer.graphics[key].attributes, 'geometry':gLayer.graphics[key].geometry});
    }
	
     store.set('graphics', {UUID: getUUID(), lastUpdate: new Date(), features: grArr})

(for your reference, UUID comes from the following functions)
    
    function generateUUID(){
    var d = new Date().getTime();
    var uuid = 'xxxxxxxx-xxxx-topo-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        var r = (d + Math.random()*16)%16 | 0;
        d = Math.floor(d/16);
        return (c=='x' ? r : (r&0x7|0x8)).toString(16);
    });
    return uuid;
    };
    function getUUID(){
     if( store.get('topo_'+window.AREA+'_UUID') )
	return store.get('topo_'+window.AREA+'_UUID')
     else
	UUID = generateUUID()
	store.set('topo_'+window.AREA+'_UUID', UUID)
	return UUID
    }

**Comment by marcuswestin** [comment]
@klombomb: After you push into an array, make sure to `store.set(key, theArray)`. Feel free to reopen with more info.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with a bunch of plugins that support common use cases like updating stored objects, performing common operations like push/shift/assign, and declaring default values for any given keys.

If you update to the [latest version(https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)

```js
store.push('foo', 'bar')
store.push('foo', 'cat')
store.get('foo') == ['bar', 'cat']
```

**Comment by Mattwmaster58** [comment]
@marcuswestin store.push() is not a function in store.modern(2.0.3), but it is in store.everything(2.0.3)
