### ISSUE TITLE
is there update method?

### ISSUE THREAD

**Issue by craigcosmo** [marcuswestin/store.js#136]
Is there update method? This feature can not be missing

**Comment by whitehat101** [comment]
You must mean the `set` method:

```
// Store an object literal - store.js uses JSON.stringify under the hood
store.set('user', { name: 'marcus', likes: 'javascript' })
```

Thankfully this feature is not missing. Store.js would be exceptionally difficult to use without the `set` method.

**Comment by craigcosmo** [comment]
```
store.set('user', { name: 'marcus', likes: 'javascript' });

console.log(store.get('user').name ) // marcus
```

```
store.set('user').likes = 'javascript';

console.log(store.get('user').name) // null
```
obviously you can't update user object. You can only set new one.

**Comment by yanpeipan** [comment]
store.set('user', store.get('user'))

**Comment by craigcosmo** [comment]
@yanpeipan  you just basically override, there is no value updated doing that.

**Comment by LucianDavies** [comment]
I have not tested it out but what if you use lodash defaultsDeep

var newvalues = {key: updatedvalue}

``store.set('user', _.defaultsDeep( newvalues, store.get('user')))

**Comment by yanpeipan** [comment]
@craigcosmo  store.set('user', {...store.get('user'), key: 'value'})

**Comment by marcuswestin** [comment]
@craigcosmo: store.js is a simple key-value store. It sound like what you're looking for is something like an ORM, which I think is outside the scope of this project.
Feel free to reopen with more info

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with a bunch of plugins that support common use cases like updating stored objects, performing common operations like push/shift/assign, and declaring default values for any given keys.

If you update to the [latest version(https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)

**Comment by amitpatil321** [comment]
var obj = store.get("user");
obj.likes = "php";
store.set("user", obj);
