### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by michaelzoidl** [marcuswestin/store.js#137]
Short question, what do you think about auto-encryption for the saved data?
I know on browser-side it's not important, but i think on node-side it would be a interesting feature.

I'm developing a electron-app and currently searching a kind of a database to save some data, store.js would be a good solution in my case - but i've to encrypt the saved data.

I found some [gist](https://gist.github.com/nekman/7124141)  where some guy prototyped a possible solution.

salute

**Comment by marcuswestin** [comment]
store.js v2 is almost complete, and has support for plugins. See see https://github.com/marcuswestin/store.js/tree/v2-dev/addon for examples. You'd simply add a new file there that adds `get` and `set` functions that encrypts and decrypts `data`. It would transparently work on all the storage engines (https://github.com/marcuswestin/store.js/tree/v2-dev/storage)

**Comment by marcuswestin** [comment]
Would accept a PR for a version 2 add-on. See https://github.com/marcuswestin/store.js/tree/v2-dev or hold for a release in the new year.

**Comment by marcuswestin** [comment]
I don't think encryption would be meaningful since the private key would have to be shipped to the browser along with store.js. Though encryption really isn't my strong suite, so let me know if I'm wrong about this and we can create an appropriate plugin!
