### ISSUE TITLE
How to append data to object literal?

### ISSUE THREAD

**Issue by NetOperatorWibby** [marcuswestin/store.js#142]
Hello everyone!

I have code like this:

```
    store.set("history", {
      id: someID
      urls: [{
        url: someURL
      }]
    });
```

And this works wonderfully. However, I would like the ability to append a new `url` to my `urls` object to the specific `id` (I have things being creating dynamically). I hope I'm making sense, haha.

Can anyone help me out?

**Comment by djm61** [comment]
Something like this perhaps?  Note: I have not tested this code at all, so no promises.
```javascript
var h = store.get("history");
h = h[someID].urls.push(someURL2);
store.set("history", h);
```

**Comment by NetOperatorWibby** [comment]
Hmm, that *looks* like it could work. I ended up going with `fs.writeFile` and appending my data to a text file in the meantime. I will test this and report back though.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with a plugin that supports common operations like `push()`.

If you update to the [latest version(https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)

**Comment by NetOperatorWibby** [comment]
Huh, that's interesting. I don't quite remember what I was using this library for 2 years ago but thanks for the update!
