### ISSUE TITLE
Private mode fall back needed

### ISSUE THREAD

**Issue by elipeters** [marcuswestin/store.js#145]
I think an option to discretly fail on isLocalStorageNameSupported would be preferable in some instances. It can be embarassing to announce that my website won't work on your phone because you choose to view it in a way you want to.

In ios my script is interupted and the site hangs which is another issue.

**Comment by elipeters** [comment]
a non issue really

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for Safari private mode.

If you update to the latest version using the [v1 backcompatible build](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)
