### ISSUE TITLE
LZ-Compression?

### ISSUE THREAD

**Issue by TJKoury** [marcuswestin/store.js#154]
Any interest in including this as an option?

**Comment by marcuswestin** [comment]
store.js v2 is almost complete, and has support for plugins. See see https://github.com/marcuswestin/store.js/tree/v2-dev/addon for examples. You'd simply add a new file there that adds get and set functions that compresses and decompresses data. It would transparently work on all the storage engines (https://github.com/marcuswestin/store.js/tree/v2-dev/storage)

**Comment by marcuswestin** [comment]
I would accept a PR with a version 2 add-on implementation of compression.
