### ISSUE TITLE
Login broken on Safari (IOS and Mac) with private browsing enabled.

### ISSUE THREAD

**Issue by john-turman** [marcuswestin/store.js#155]
With private browsing enabled, Safari is unable to write the login token to local browser storage when the user is logging in, causing the login to fail.  

Until this is fixed, the workaround is to disable private browsing.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for Safari private mode.

If you update to the latest version using the [v1 backcompatible build](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)
