### ISSUE TITLE
chrome.storage.local support?

### ISSUE THREAD

**Issue by nathanph** [marcuswestin/store.js#159]
What are your thoughts on supporting chrome.storage.local?

chrome.storage.local > localStorage > userData

Is that something you would be interesting in adding/having added to this project? Or should I focus on doing that in a project separate from this?

**Comment by nbubna** [comment]
If you use the extensible [store2](https://github.com/nbubna/store), you get a full-featured wrapper as easy as:
```
var cstore = store.area('chrome', chrome.storage.local);
cstore('foo', {bar:true});
store.chrome === cstore;// true! for those who don't want to pass a ref around
```

**Comment by nathanph** [comment]
Thanks @nbubna! I had looked at [store2](https://github.com/nbubna/store), but I didn't see that.

**Comment by marcuswestin** [comment]
[Store.js v2.0](https://github.com/marcuswestin/store.js/blob/master/README.md) was just released and supports the ability of plugging in additional storage methods (https://github.com/marcuswestin/store.js/blob/master/README.md#user-content-write-your-own-storage).

Would you be up for writing a chrome.storage.local plugin?

Cheers!

**Comment by Akkuma** [comment]
@nbubna Your example wouldn't work if I correctly read your docs/code. The chrome.storage.local API is not StorageInterface compatible and is async.

**Comment by nbubna** [comment]
Ah, yeah, definitely not compatible if it's async. Probably not with Store.js v2.0 either at this point. You need something in the async category, like https://github.com/localForage/localForage

**Comment by marcuswestin** [comment]
There is an async API coming (#181). With that in place this becomes relevant again.
