### ISSUE TITLE
Regular expression error?

### ISSUE THREAD

**Issue by newbeex** [marcuswestin/store.js#162]
In IE7, keys cannot start with a digit or contain certain chars.

But the regular expression is replaced by a string "d"

var ieKeyFix = function(key) {
    return key.replace(**/^d/**, '**_$&').replace(forbiddenCharsRegex, '**_')
}

**Comment by marcuswestin** [comment]
@newbeex: sorry, I don't understand what the problem is. If you have an example that isn't working the way you expect, please include that.
