### ISSUE TITLE
it is not working in Browser Private Mode

### ISSUE THREAD

**Issue by nndung179** [marcuswestin/store.js#168]
Hi currently. I am using this lib in project. But when I tested my application in Private mode. Here what it comes out:

+ `Safari private mode`
-- Desktop: not working
-- Mobile: not working

+ `Chrome private mode`
-- Desktop: working 
-- Mobile: not working

**Comment by nbubna** [comment]
Chrome mobile is only a wrapper around iOS Safari.

**Comment by vjarysta** [comment]
See https://github.com/marcuswestin/store.js/issues/42

**Comment by marcuswestin** [comment]
Also see #156: 

store.js v2 is almost complete, and has a cookie storage option (among a bunch of additional addon features - see https://github.com/marcuswestin/store.js/tree/v2-dev/storage & https://github.com/marcuswestin/store.js/tree/v2-dev/addon). Stay tuned for an official release.

**Comment by nndung179** [comment]
@marcuswestin ok I will try
