### ISSUE TITLE
Feature Request - setDefault() method

### ISSUE THREAD

**Issue by hdodov** [marcuswestin/store.js#173]
I don't know if feature requests are accepted here. Here's one, though.

I know that `store.get("key", 5)` would return `5` in case `key` has not been found in the storage. Providing that default value is pretty useful functionality. However, if you need to get `key` at several different places in your app, you need to specify the default value every time, which can be pretty annoying.

My proposal is to have a `setDefault()` method that could do this:
```
store.setDefault("key", 5);
```
Which saves `5` as a default value of `key` internally. After that, if `store.get("key")` is called and no data was found, `5` is returned (unless another default value is explicitly given).

Example:
```
store.get("key", 5); // 5
store.get("key"); // undefined
store.setDefault("key", 5);
store.get("key"); // 5
store.get("key", 10); // 10
```
This can be a bit confusing, since you don't know whether the returned value is actual storage data, or internal default data. _But._ It's a good to guarantee a value. If you initialize your crucial values when your app starts, you know that you won't be getting `undefined` where it can be problematic.

Perhaps a `setDefaults()` method would be even better:
```
store.setDefaults({
    foo: "bar",
    key: 5,
    six: 6
});
```
Thanks!

**Comment by nbubna** [comment]
Why wouldn't you just set those values? What's the use case for having them be transient?

**Comment by kosinix** [comment]
Yeah. Why not just:

`if (store.get("key") == undefined){
        store.set("key", 5);
}`


All succeeding calls would have 5 as default anywhere in your app.

> However, if you need to get key at several different places in your app, you need to specify the default value every time, which can be pretty annoying.

Or just wrap your code in a global function. Your problem can be easily solved on the app-level without the need to change the store.js API.

**Comment by hdodov** [comment]
Yeah, wrapping it is what I ended up doing and it works:
```
Storage = (function () {
    var _stored = {};

    return {
        init: function (defaults) {
            _.each(defaults, function (defaultVal, key) {
                _stored[key] = store.get(key, defaultVal);
            });
        },

        get: function (prop) {
            return _stored[prop];
        },

        set: function (prop, val) {
            if (typeof prop === "string") {
                _stored[prop] = val;
                store.set(prop, val);
            }
        }
    };
})();
```

That:
`if (store.get("key") == undefined){ store.set("key", 5); }`
Would only work if a type of storage is available, meaning that `key` can still be `undefined`. With my snippet, doing this:
```
Storage.init({
    key: 5,
    bar: 6
});
```
Means that `Storage.get("key")` will always return either a saved value or the initialized value. You won't be getting `undefined`.

This was my suggestion initially. But now that I think of how easily I made it work by myself, it isn't probably _that_ groundbreaking.

Thanks for the responses!

**Comment by nbubna** [comment]
Ah, yes, just doing a ```set``` first would fail with this library. Sorry, i follow this repo, but i actually maintain https://github.com/nbubna/store which would not return undefined if localStorage were unavailable, but just keep the set value in memory.

**Comment by marcuswestin** [comment]
This is now supported in store.js v2 via the [defaults plugin](plugins/defaults). See https://github.com/marcuswestin/store.js/blob/master/README.md for more info!

**Comment by marcuswestin** [comment]
See https://github.com/marcuswestin/store.js/blob/master/plugins/defaults_test.js for example usage.
