### ISSUE TITLE
Stores double quotes as part of a string

### ISSUE THREAD

**Issue by Bouncey** [marcuswestin/store.js#174]
In one part of my app I am storing a string in localStorage to correctly set the app theme on page load

```js
const newTheme = !theme || theme === 'default' ? 'night' : 'default';
store.set('fccTheme', newTheme);
```

When I come to retrieve the theme from localStorage in a script tag I have to do

```js
if (typeof localStorage !== 'undefined') {
    const fccTheme = localStorage.getItem('fccTheme');
    if (fccTheme === '"night"') {
      document.body.classList.add('night');
    }
   }
```

From what I can work out 
```js
const fccTheme = localStorage.getItem('fccTheme');
typeof fccTheme === 'string' // true
fccTheme === 'night' // false
fccTheme == 'night' // false
fccTheme === '"night"' // true
```

**Comment by marcuswestin** [comment]
Hi!

LocalStorage only stores string values (it can't store numbers, objects, arrays, etc). One of the key benefits of store.js is the ability to store any type of value, and it does it using JSON to serialize values to a string (which is then stored in the underlying localStorage, sessionStorage, etc). It also has the benefit of using a storage mechanism that works across all browsers, which means that your site will work properly in eg IE7, FF4 and Safari Private mode, whereas your current approach would break in all those cases. 

So what you should do is use `store.get("fccTheme")` instead :)

If you insist on accessing it using localStorage directly, you should definitely set the value using localStorage directly as well.

I also suggest using the new v2.0 version which supports more browsers and has added functionality: https://raw.githubusercontent.com/marcuswestin/store.js/v2-dev/dist/cross-browser.min.js

Cheers!
Marcus
