### ISSUE TITLE
Module not found: Error: Can't resolve 'store'.

### ISSUE THREAD

**Issue by amino-studio** [marcuswestin/store.js#176]
v2.0.0

I build bundle via WebPack.

Code:
```
import store from 'store';
```

I've switched to 1.3.20 - everything smooth and nice.

**Comment by marcuswestin** [comment]
Should be fixed in 2b6cf4de50bb5 and v2.0.1. Apologies for the broken build!

**Comment by marcuswestin** [comment]
Just verified that this works with v2.0.1:

test.js
```js
import store from 'store'
store.set('foo', 'bar')
console.log(store.get('foo') == 'bar')
```

`> webpack test.js test.out.js && node test.out.js`

Let me know if anything else isn't right for you!

Cheers,
Marcus

**Comment by amino-studio** [comment]
Working! Thank you :-)
