### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by pannous** [marcuswestin/store.js#178]
setting `store.storage='localStorage'` has no effect (node.js).
 if this is by design please make it a getter only

**Comment by marcuswestin** [comment]
I see what you mean. Give me some time to think about what the right thing to do here is.

Making it a getter doesn't work properly in older browsers, so I'm not too keen on that.

Maybe we should just remove that property... What do you think?

**Comment by pannous** [comment]
Sounds fine. Tangentially related: How DO I set/use localStorage? require('localStorage') has a different API

**Comment by AaronLlanos** [comment]
localStorage is a browser side storage system which comes built in to all modern browsers.  To use a storage system for node you would need to look into 3rd party libeanies. Why would you want to not use a standard dB like mysql lite?

**Comment by AaronLlanos** [comment]
Upon further review of the READMEs:
store.js works as expected in node.js, assuming that global.localStorage has been set:

```
global.localStorage = require('localStorage')
var store = require('./store')
store.set('foo', 1)
console.log(store.get('foo'))
```
You can find the library to run on node [here](https://www.npmjs.com/package/localStorage)
