### ISSUE TITLE
Add info on storage limits

### ISSUE THREAD

**Issue by marcuswestin** [marcuswestin/store.js#186]
Noting limits and behavior on excess would be meaningful. See https://www.html5rocks.com/en/tutorials/offline/quota-research/#toc-overview

**Comment by Krizzu** [comment]
Hey Marcus, I'm going to work on this one!
Would You like to extend README file with limits of storages or creating a separate doc file would be preferred?

**Comment by marcuswestin** [comment]
Thank you! 🙏

Not sure, haven't thought that through yet :) I'll leave it to you to figure out what's best!

**Comment by marcuswestin** [comment]
See also #81 which points to http://stackoverflow.com/questions/7245462/html5-localstorage-space-limit-on-ipad-safari (may not be very relevant, but thought I'd collect info in one place).

**Comment by marcuswestin** [comment]
See also #56

**Comment by marcuswestin** [comment]
This is was done by @Krizzu and myself in #203 and #208!

**Comment by Krizzu** [comment]
I like it more your way, great!
