### ISSUE TITLE
Add README status badges

### ISSUE THREAD

**Issue by marcuswestin** [marcuswestin/store.js#188]
E.g circleci status, download count (https://github.com/localForage/localForage/blob/master/README.md), etc

**Comment by AaronLlanos** [comment]
@marcuswestin  I can take this for you. Did you have a CI system that you want to integrate with in particular?

**Comment by AaronLlanos** [comment]
#207 PR created

**Comment by marcuswestin** [comment]
Niiiiice, thanks @AaronLlanos! Merged and released :)

**Comment by marcuswestin** [comment]
It looks like the downloads badge isn't working. Can you please double check that it's linked to the right URL and image?

**Comment by marcuswestin** [comment]
@AaronLlanos Currently takes me to a 404 GitHub page, at least on mobile

**Comment by AaronLlanos** [comment]
@marcuswestin , Hmm well you have two options for the downloads link. Would you rather have it point to the repo itself or go to npm?

**Comment by marcuswestin** [comment]
Thanks for fix and PR @AaronLlanos! Sorry for my delay in merging.
