### ISSUE TITLE
Expire and Events plugins conflict with each other, results in RangeError: Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by Iwasawafag** [marcuswestin/store.js#235]
I've been repeatedly getting `RangeError: Maximum call stack size exceeded` errors when tried to use the library in combination with `expire` and `events` plugins.

Here's the test case: https://repl.it/IRXf/1

All you need to have is one expiration record for the key you're trying to update and it breaks on the next `set()` call.

Browser: Chrome 58.0.3029.110 (64-bit)

**Comment by marcuswestin** [comment]
Looking at this now
