### ISSUE TITLE
2.0.8 - No supported storage has been added

### ISSUE THREAD

**Issue by stunaz** [marcuswestin/store.js#236]
After upgrading from `2.0.4` to` 2.0.8`, i got this error:

`Error: store.js: No supported storage has been added! Add one (e.g store.createStore(require('store/storages/cookieStorage')) or use a build with more built-in storages (e.g https://github.com/marcuswestin/store.js/tree/master/dist/store.legacy.min.js)`

**Comment by marcuswestin** [comment]
Shoot! Can you give me more info on how you include store.js in your app (or create the store)?

**Comment by marcuswestin** [comment]
I'm trying to reproduce this and not having any luck.

**Comment by stunaz** [comment]
```javascript
import store from 'store';
const token = store.get('token'); // or set ...
```

never had to specified a storage or anything else

**Comment by stunaz** [comment]
Reverted to 2.0.4, and it is working again

**Comment by marcuswestin** [comment]
Bizarre. Thanks. What's the environment you're testing in? (e.g browser version)

**Comment by stunaz** [comment]
browser -chrome

**Comment by marcuswestin** [comment]
Ok, got repro. Will fix asap

**Comment by stunaz** [comment]
Thanks

**Comment by marcuswestin** [comment]
This is a really silly bug. I'm amazed that none of the tests covered it. Sorry for the hassle :/

**Comment by stunaz** [comment]
no worries, wondering why I am the first to notice

**Comment by marcuswestin** [comment]
It's only been out for a few hours - that may be why :) Ok, v2.0.9 has been released.

**Comment by marcuswestin** [comment]
Thanks for prompt responses @stunaz! Going back to bed :)

**Comment by stunaz** [comment]
worked, thanks
