### ISSUE TITLE
Error: No supported storage has been added! Add one (e.g store.createStore(require('store/storages/cookieStorage'))

### ISSUE THREAD

**Issue by sahiljain112** [marcuswestin/store.js#239]
```
import store from 'store';
const set = (key, value) => store.set(key, value); 
const get = key => store.get(key);
```

This is my code. The version I'm using is v2.0.9.
I checked the source code and it shouldn't give me that error since the storage array is being imported from storage/all. Why am I getting this error?

**Comment by marcuswestin** [comment]
Can you check store.version please?

**Comment by marcuswestin** [comment]
Hey @sahiljain112,

I added a test for this issue (https://github.com/marcuswestin/store.js/blob/master/tests/bugs/gh-239.js). It's currently passing under v2.0.9. Can you double check and help me create a repro please?

**Comment by marcuswestin** [comment]
@dyegolara I've merged a few additional PRs and added a few small features. Current version is 2.0.11. Can you please verify that the latest version is broken for you, and if so help me figure out how to reproduce your issue? Currently all out tests are passing on all browsers.

**Comment by marcuswestin** [comment]
I'm still unable to repro. v2.0.9, v2.0.10 and v2.0.11 all work as expected for me:

```
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<script type="text/javascript" src="https://unpkg.com/store@2.0.9/dist/store.legacy.min.js"></script>
<script type="text/javascript">
	store.set('foo', 'bar')
	console.log(store.get('foo'))
</script>
</body>
</html>
```

@sahiljain112 @dyegolara Please help me figure out how to reproduce your issue.

**Comment by dyegolara** [comment]
Just made the update to 2.0.11, everything works fine!!

Thanks man, you have an awesome library, very useful for a lot of users and companies, you have made the web a better place. Keep being cool!

**Comment by marcuswestin** [comment]
👍  Thanks @dyegolara  :)

**Comment by sahiljain112** [comment]
Hey @marcuswestin . Everything is working as expected in v2.0.9.
I triggered a build with v2.0.8 for which this error was displayed. Thanks for the help!
