### ISSUE TITLE
Strange symbols when using store.js

### ISSUE THREAD

**Issue by liusjose5** [marcuswestin/store.js#275]
Hi Marcus, I've been using your library for quite some time now, but I'm facing a new issue: it seems like whenever I store some values using store.js it messes with the character coding.
I'm attaching a screenshot of the console so you can see the problem. Any ideas around this? I've tried playing with the meta charset to no avail.
Thanks

<img width="389" alt="screen shot 2018-04-15 at 11 00 21 am" src="https://user-images.githubusercontent.com/17604813/38780529-8431aeb0-409d-11e8-83fd-b6c61f37c458.png">

**Comment by lianee** [comment]
You're seeing strange chars because you're using the compression plugin. As you can see, store.get correctly retrieve the correct value

**Comment by lianee** [comment]
It is doing the right thing, you store things and retrieve them exactly as you stored them, so you don't need a work-around...
If you really don't want your data compressed, then you need to "not" include the compression plugin. Unfortunately, as the builds are right now, you just include them all... or none, or you'll have to make a custom build, see #238

**Comment by liusjose5** [comment]
Got it. Thanks very much for the info.
