### ISSUE TITLE
Safari Private browsing mode appears to support localStorage, but doesn't

### ISSUE THREAD

**Issue by tjarratt** [marcuswestin/store.js#42]
Apparently this is by design. When Safari (OS X or iOS) is in private browsing mode, it appears as though localStorage is available, but trying to call .setItem throws an exception. 

store.js line 73
"QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota."

What happens is that the window object still exposes localStorage in the global namespace, but when you call setItem, this exception is thrown. Any calls to .removeItem are ignored.

I believe the simplest fix (although I haven't tested this cross browser yet) would be to alter the function isLocalStorageNameSupported() to test that you can also set some value.

currently:

```
function isLocalStorageNameSupported() {
    try { return (localStorageName in win && win[localStorageName]) }
        catch(err) { return false }
}
```

proposed:

```
function isLocalStorageNameSupported() {
    try { 
        var supported = (localStorageName in win && win[localStorageName]);
        if (supported) { localStorage.setItem("storage", ""); localStorage.removeItem("storage");
        return supported;
    }
    catch(err) { return false }
}
```

Of course it's kind of silly to call this every time you want to check that storage is supported, so you could memoize it, but you get the idea.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for Safari private mode.

If you update to the latest version using the [v1 backcompatible build](https://github.com/marcuswestin/store.js/blob/master/dist/store.v1-backcompat.min.js) you will automatically get this functionality plus a bunch more :)

**Comment by sighWang** [comment]
@marcuswestin thank you for update. Which commit support this feature?
