### ISSUE TITLE
Feature request: Encrypted storage

### ISSUE THREAD

**Issue by piotr-cz** [marcuswestin/store.js#50]
### Goal

Use encryption for storing data for non-public app areas.
### Description

As far as I know, browsers store DOM storage on disk in unencrypted files, DOM storage is accessible from all domain paths (except IE UserData) and doesn't expire. 

This may be considered as security issue on shared workstations in cases when client-side app doesn't clear user data (browser crash/ closed window) or browser decides to keep them (temporary files).

I see the simplest solution in encrypting storage data after serializing to JSON and decrypt before deserializing.

It's up to the developer to come up with idea how to obtain secure key/ token; assuming encrypted storage makes sense for non-public areas (user is logged in), one can possibly use server-side unique session token.
Once server-side session expires, token is not available anymore. When there is no token, previously saved data theoretically become undecryptable junk (and may be removed client-side on next execution).

This should limit access to user data.

Drawback: Storage values take quite more space (depends on encoding);

Inspiration: [dojo.storage.encrypted](http://jensarps.de/2010/04/15/encrypted-client-side-storage-with-dojo/)
### Implementation

Configuration for [Crypto.js](http://code.google.com/p/crypto-js/),  but any crypt library with methods `encrypt( value )` and `decrypt( encrypted )` should work:

``` javascript
store.crypt = {
    key: App.token, // ie. 'c015dc1d6028a6815ac944c8512c10db',
    encrypt: function( plaintext ) {
        return CryptoJS.AES.encrypt( plaintext, this.key ).toString();
    },
    decrypt: function( encrypted ) {
        return CryptoJS.AES.decrypt( encrypted, this.key ).toString( CryptoJS.enc.Utf8 );
    }
}
```

Proposed changes to store.js code (didn't test):

``` javascript
store.serialize = function(value) {

    var serialized = JSON.stringify( value );

    if ( store.crypt ) { serialized = store.crypt.encrypt( serialized ); }

    return serialized;
}


store.deserialize = function(value) {

    if ( typeof value !== 'string' ) { return undefined; }

    if ( store.crypt )
    {
        try {
            value = store.crypt.decrypt( value );
        } catch (e) {
            return undefined;
        }
    }

    return JSON.parse( value );
}

```

I'd like to discuss this idea with more proficient developers as I don't have much experience with client-side encryption.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for plugins! See https://github.com/marcuswestin/store.js#user-content-write-your-own-plugin for a quick description of how to write one.

If you're up for writing one I'll definitely accept a PR!
