### ISSUE TITLE
Support for sessionStorage?

### ISSUE THREAD

**Issue by danielfarrell** [marcuswestin/store.js#53]
Is there any interest from anyone else in support for sessionStorage as an alternative to localStorage?

There are times when I just want to keep the data for the browser session.  Mostly logged-in user info for a client side app.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for sessionStorage!

If you update to the latest version you will automatically get this functionality plus a bunch more :)

The docs explain how to create a custom build - to get one that only uses sessionStorage, you can do this:

```js
// Example custom build usage:
var engine = require('../store-engine')
var storages = [require('store/storages/sessionStorage')
var plugins = []
var store = engine.createStore(storages, plugins)
store.set('foo', 'bar')
```
