### ISSUE TITLE
Add hook for storage event

### ISSUE THREAD

**Issue by aensley** [marcuswestin/store.js#73]
Would it be possible to add a way to hook into the [HTML5 `storage` event](http://dev.w3.org/html5/webstorage/#the-storage-event) with this library?

[Demo of the functionality I'm looking for](http://html5demos.com/storage-events) (but doesn't use store.js, obviously).

I'm thinking something like:

``` javascript
// All Windows / Tabs:
store.on('keyName', function(s){
    console.log(s.newValue);
});

// Window / Tab 1:
store.set('keyName', 'testValue');

// All other Windows / Tabs:
// 'testValue' is logged.
```

I'm implementing my own solution for this with the following code:

``` javascript
// All Windows / Tabs:
// Hook into the storage event
$(window).on('storage', function(e){
    // Keys we actually care about.
    var keys = ['timeStamp', 'key', 'oldValue', 'newValue', 'url'], newEvent = {};
    e = e.originalEvent; // jQuery puts the original event here
    for (var i in keys) {
        i = keys[i];
        if (i.substr(3) === 'Value') {
            // Get the value back just like we put it into store.set()
            newEvent[i] = store.deserialize(e[i]);
        } else {
            newEvent[i] = e[i];
        }
    }

    // Send the event to global listeners that want to know about all storage changes.
    newEvent.type = 'localStorage';
    $(document).trigger(newEvent);
    // Send the event to listeners for this key only.
    newEvent.type = newEvent.key + '.localStorage';
    $(document).trigger(newEvent);
});

$(document).on('keyName.localStorage', function(e){console.log(e.newValue);});

// Window / Tab 1:
store.set('keyName', 'testValue');

// All other Windows / Tabs:
// 'testValue' is logged.
```

This seems like the perfect addition to this library. It would make cross-window/tab communication with store.js dead-simple. Want all of your web app tabs to know you just got a new message in the current tab? Just call `store.set('newMessage', 'hey!');`.

Of course, it would only work when localStorage is supported, but it would be easy enough to indicate in the `.on()` function's return value whether or not listening is enabled.

I can submit a pull request if you're interested.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for storage events and storage value observations: https://github.com/marcuswestin/store.js#user-content-list-of-all-plugins

If you update  you will get this functionality plus a bunch more :)
