### ISSUE TITLE
Synchronisation with server

### ISSUE THREAD

**Issue by imjacobclark** [marcuswestin/store.js#80]
Hi,

I would be interested in implementing 'sync with server' functionality for a Key/Value store such as Redis/Memcached, possibly even MongoDB/CouchDB too. 

Why? One of the main uses of localStorage is to hold user inputted data locally incase of an unexpected interrupt that forces the browser or input device to crash. Holding the data in localStorage then allows the user to quickly resume to what they were doing without loosing already inputted data.

I feel providing a sync helper method that produces a PUT/POST RESTful request to a URL would be fantastic functionality for this library.

Jacob.

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released with support for plugins! See https://github.com/marcuswestin/store.js#user-content-write-your-own-plugin for a quick explanation on how you can write one that will sync with your server.
