### ISSUE TITLE
does it have a localstorage's 5MB limit?

### ISSUE THREAD

**Issue by xiaok** [marcuswestin/store.js#81]
thanks.

**Comment by dmarcos89** [comment]
Hi @marcuswestin , great work!
Do you have any idea which is the limit on iPad Safari?
Thanks!

**Comment by marcuswestin** [comment]
@dmarcos89: I don't, but some quick googling turns up lots of information. See e.g http://stackoverflow.com/questions/7245462/html5-localstorage-space-limit-on-ipad-safari and its links - if you spend 30 min researching it I expect you'll have some pretty good information.

Cheers!
