### ISSUE TITLE
IE fails if key starts with a number!

### ISSUE THREAD

**Issue by monolithed** [marcuswestin/store.js#83]
IE fails if the key starts with a number!

Please add the following line to the `ieKeyFix`:

``` js
.replace(/^d/, '___$&')
```

**Comment by marcuswestin** [comment]
See https://github.com/marcuswestin/store.js/commit/de5fcf75a86acb96360c7898fec5617903d42f30 for update with proper fix

**Comment by monolithed** [comment]
Oh, thanks, it's my fail (

**Comment by marcuswestin** [comment]
Also thanks to you that it got fixed at all! 🙏 :)
