### ISSUE TITLE
sessionStorage implementation

### ISSUE THREAD

**Issue by ancashoria** [marcuswestin/store.js#90]
Hi, thanks for your work, I really love the userData hack.

I would like to know how hard would it be for store.js to support sessionStorage ? Is it enough to change localStorageName = 'localStorage' to 'sessionStorage' ?

**Comment by marcuswestin** [comment]
Store.js v2.0 has been released!

If you update to the [latest version](https://github.com/marcuswestin/store.js/blob/master/dist/store.everything.min.js) you will automatically get this functionality plus a bunch more :)
