### ISSUE TITLE
I built a helpful Store.js wrapper, and I'd love your opinion

### ISSUE THREAD

**Issue by evitolins** [marcuswestin/store.js#95]
Hi Marcus,

I'm really enjoying store.js and ended up needing with some extra features.  So naturally, I started creating what I needed.

I wanted to have a way to keep a variable "in-sync" with the store-js data, so that I do not need to query store-js' local storage constantly.  Maybe this is redundant to do so (and I'm curious what you think), but I created a wrapper that leverages store-js, while maintaining a synced local variable.

It provides a few more perks, like defaults values and basic "schema" syncing.  Although, this first pass is pretty limited.

Here's my first pass at what I envisioned: 
https://gist.github.com/evitolins/5e6e835a884228ef8617

Anyways, thanks again for store-js!  Look forward to hearing what you think about "StoreFront". :)

Cheers,
- Eriks

**Comment by marcuswestin** [comment]
Hey @evitolins,

Store.js v2.0 has been released with [support for plugins](https://github.com/marcuswestin/store.js#user-content-plugins)! If any of the functionality you added is stuff you think would be useful in store.js, here's some quick text on how to write new plugins: https://github.com/marcuswestin/store.js#write-your-own-plugin

Cheers!
