### ISSUE TITLE
Store is undefined when loading into a page that already uses AMD

### ISSUE THREAD

**Issue by kgust** [marcuswestin/store.js#96]
We tried loading store.js into a site that had require.js (which was outside our control and loaded modules unrelated to what we were doing).

We use window.store to access store.  In this case, `define.amd` was defined so the code tries to call `define(store)` instead.

Because `window.store` is not defined, our code doesn't run.

NOTE: This is related to Issue #91 but is a different problem.

**Comment by marcuswestin** [comment]
This may very well have been solved by 7c65e0a646c9c4743. @kgust, can you please verify and/or close?

Thanks for the patience!

**Comment by kgust** [comment]
I can't verify currently with the problematic site, but this should fix it.

**Comment by marcuswestin** [comment]
Thanks Kevin
